### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by orangejacky** [SkyTNT/midi-model#3]
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\midi-model-main\midi-model-main\train.py", line 320, in <module>
    warmup=opt.warmup_step, max_step=opt.max_step)
  File "C:\Users\admin\Downloads\midi-model-main\midi-model-main\train.py", line 87, in __init__
    n_inner=n_inner, flash=flash)
  File "C:\Users\admin\Downloads\midi-model-main\midi-model-main\midi_model.py", line 26, in __init__
    self.net = self.net.to_bettertransformer()
  File "C:\Users\admin\python\lib\site-packages\transformers\modeling_utils.py", line 3422, in to_bettertransformer
    from optimum.bettertransformer import BetterTransformer
  File "C:\Users\admin\python\lib\site-packages\optimum\bettertransformer\__init__.py", line 14, in <module>
    from .models import BetterTransformerManager
  File "C:\Users\admin\python\lib\site-packages\optimum\bettertransformer\models\__init__.py", line 16, in <module>
    from .attention import _llama_prepare_decoder_attention_mask
  File "C:\Users\admin\python\lib\site-packages\optimum\bettertransformer\models\attention.py", line 20, in <module>
    from transformers.models.llama.modeling_llama import apply_rotary_pos_emb, repeat_kv
ImportError: cannot import name 'repeat_kv' from 'transformers.models.llama.modeling_llama' (C:\Users\admin\python\lib\site-packages\transformers\models\llama\modeling_llama.py)

**Comment by SkyTNT** [comment]
try `pip install -U transformers optimum`

**Comment by orangejacky** [comment]
Traceback (most recent call last):
  File "app.py", line 196, in <module>
    model = MIDIModel(tokenizer).to(device=opt.device)
  File "C:\Users\admin\python\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 54, in to
    return super().to(*args, **kwargs)
  File "C:\Users\admin\python\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\Users\admin\python\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\admin\python\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\admin\python\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\admin\python\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\admin\python\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by SkyTNT** [comment]
you need install cuda and pytorch gpu.

**Comment by SkyTNT** [comment]
You should learn to solve problems on your own. Don't keep asking me.
