### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by brainchen2020** [SkyTNT/midi-model#8]
我更新了代码下来，生成的时候大概率会碰到这个错误。
 Scores 会传入nan的情况
 
CUDA Version: 11.8
torch==2.0.1cu118
transformers==4.33.1
pytorch-lightning==2.0.7

 
 

### 具体：
 打印sample_top_p_k参数，model.sample_top_p_k(scores, top_p, top_k)
 def sample_top_p_k(self, probs, p, k):
           # Debugging code
        print("probs:", probs)
        print("Contains inf:", torch.isinf(probs).any())
        print("Contains nan:", torch.isnan(probs).any())
        print("Contains negative:", (probs < 0).any())

probs: tensor([[[nan, nan, nan,  ..., nan, nan, nan]]], device='cuda:0')
Contains inf: tensor(False, device='cuda:0')
Contains nan: tensor(True, device='cuda:0')
Contains negative: tensor(False, device='cuda:0')
generating:  77%|███████▋  | 1149/1493 [01:55<00:34,  9.94it/s]
Traceback (most recent call last):
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\Data\Git Repository\midi-model\app.py", line 128, in run
    for i, token_seq in enumerate(generator):
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "D:\Data\Git Repository\midi-model\app.py", line 62, in generate
    sample = model.sample_top_p_k(scores, top_p, top_k)
  File "D:\Data\Git Repository\midi-model\midi_model.py", line 72, in sample_top_p_k
    next_token = torch.multinomial(probs_sort.reshape(-1, shape[-1]), num_samples=1).reshape(*shape[:-1], 1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by SkyTNT** [comment]
是你自己的模型吗, 应该是模型炼炸了

**Comment by brainchen2020** [comment]
> 是你自己的模型吗, 应该是模型炼炸了

一开始我也觉得是炼炸了（我发现epoch正在训练时断开，之前的checkpoint会出问题），
后面换Base Model也会有这种情况。怎么会这样。。。

**Comment by SkyTNT** [comment]
Base Model可能就已经炸了,如果你数据量够的话可以试试从头开始炼。还可以lr小一点，应该不容易炸

**Comment by brainchen2020** [comment]
嗯，我试试从头开始

> Base Model可能就已经炸了,如果你数据量够的话可以试试从头开始炼。还可以lr小一点，应该不容易炸

**Comment by brainchen2020** [comment]
我从头开始练，loss在0.7，表现不够好的情况下也会炸。
lr=2e-4

> loading model lightning_logs\version_4\checkpoints\epoch=13,loss=0.7732.ckpt
{'is_nan': tensor(False, device='cuda:0'), 'is_inf': tensor(False, device='cuda:0')}
generating:  39%|███▊      | 575/1493 [00:33<00:52, 17.39it/s]
Traceback (most recent call last):
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\Data\Git Repository\midi-model\app.py", line 128, in run
    for i, token_seq in enumerate(generator):
  File "C:\Users\HOLA\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "D:\Data\Git Repository\midi-model\app.py", line 62, in generate
    sample = model.sample_top_p_k(scores, top_p, top_k)
  File "D:\Data\Git Repository\midi-model\midi_model.py", line 72, in sample_top_p_k
    next_token = torch.multinomial(probs_sort.reshape(-1, shape[-1]), num_samples=1).reshape(*shape[:-1], 1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by SkyTNT** [comment]
Lr 2e-4应该高了, 还有你其它参数是多少

**Comment by brainchen2020** [comment]
> Namespace(resume='', ckpt='', data='D:\\Data\\Dataset\\my_training_dataset', data_val_split=1280, max_len=4096, seed=0, lr=0.0002, weight_decay=0.01, warmup_step=1000, max_step=70000, grad_clip=1.0, batch_size_train=3, batch_size_val=3, workers_train=12, workers_val=12, acc_grad=2, accelerator='gpu', devices=-1, fp32=False, disable_benchmark=False, log_step=1, val_step=1600)
---load dataset---
train: 9408  val: 1280

**Comment by brainchen2020** [comment]
之前用的代码可以在你提供的模型下用得好好的，推理2048长度的序列也没出现过问题，继续训练也行。但现在不得，奇怪

**Comment by SkyTNT** [comment]
哪个版本的代码

**Comment by brainchen2020** [comment]
![1698583424095](https://github.com/SkyTNT/midi-model/assets/29730101/029a486f-2859-4f3f-81f6-89eb76e42dd9)

**Comment by SkyTNT** [comment]
试试把这两行注释掉，重新训练吧。
https://github.com/SkyTNT/midi-model/blob/7a3d502f42fc960c2981865425f2e5e79996b96a/train.py#L144-L145
这是为了减小显存使用做的trade-off,。
如果炸显存的话可以吧max-len从4096改到2048。

也可以试试不删除，吧`min(127, (y.shape[1] - 2) // 2)`改成一个固定的值，调高到不会炸显存的极限。

**Comment by brainchen2020** [comment]
等一下，我现在回到这个版本的代码也出错。。我感觉是我这边出了问题。。。我再检查一下

**Comment by SkyTNT** [comment]
其实我觉得还是你的学习率太高，如果你只有一个显卡的话，你的batchsize是6，那么lr应该为10的-6次方才行。

**Comment by brainchen2020** [comment]
嗯嗯，这个我记下了，training是一回事。
现在我这边用你提供的模型推理也出问题了，讲道理环境也没多少能出错的，都加载到GPU里了。。。

> 其实我觉得还是你的学习率太高，如果你只有一个显卡的话，你的batchsize是6，那么lr应该为10的-6次方才行。

**Comment by brainchen2020** [comment]
你能发下你的依赖包版本是多少吗？

**Comment by SkyTNT** [comment]
这和依赖包版本应该没关系,而且我也不是本地运行的。

**Comment by brainchen2020** [comment]
这就奇怪了，我之前用的版本代码好好的，现在推理也不行

**Comment by brainchen2020** [comment]
我现在换了最新代码，最新模型，推理时有可能会出这个错，有时又没出错，没头绪找不到源头。1024 1500 2048 generate events都测过，Toggle AMP也试过 ，神奇。
