### ISSUE TITLE
Colab fails (possibly need to downgrade gradio?)

### ISSUE THREAD

**Issue by drscotthawley** [SkyTNT/midi-model#9]
Hi! Thanks for sharing your code!  I'm really enjoying playing with you Huggingface Space.  
When I went to try the Colab notebook, the line 

````
!python app.py --max-gen 4096 --share
```
would fail with this error mesage:
```python
Traceback (most recent call last):
  File "/content/midi-composer/midi-composer/app.py", line 191, in <module>
    class JSMsgReceiver(gr.HTML):
  File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 191, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 110, in create_or_modify_pyi
    current_interface, _ = extract_class_source_code(pyi_file.read_text(), class_name)
  File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 72, in extract_class_source_code
    class_ast = ast.parse(code)
  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 192
    from gradio.events import Dependency
    ^
IndentationError: expected an indented block after class definition on line 191
```

I know that `gradio` has seen a lot of updates recently, perhaps something broke relative to your code.  What version of `gradio` have you been using to build this? 

Thanks!

**Comment by drscotthawley** [comment]
Ah yes!  `!pip install -Uqq gradio==3.45.0` (from September 2023)  was sufficient to make the error go away.  
Newer versions of `gradio` may also work.

**Comment by drscotthawley** [comment]
Although,  but now when I try it, pressing the "generate" button does not produce the nice piano-roll view that the Huggingface Space does.  That area of the GUI is completely blank.  
<img width="1075" alt="Screenshot 2023-11-10 at 8 23 44 PM" src="https://github.com/SkyTNT/midi-model/assets/13925685/93e11c1f-a9d8-4c51-9e15-52bb35310f68">

There is some text status being printed near the top of the Gradio demo, and after that text stops changing, then the audio and midi files are available. 

Perhaps some version of `gradio` in between 3.45.0 and the latest version is what is needed for full functionality.

**Comment by drscotthawley** [comment]
Aha!
`!pip install -Uqq gradio==3.41.2`
fixed it.

**Comment by drscotthawley** [comment]
Sent PR. Can close this upon acceptance.
